/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/canvases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Canvases */
        get: operations["list_canvases_api_v1_canvases_get"];
        put?: never;
        /** Create Canvas */
        post: operations["create_canvas_api_v1_canvases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Canvas Events */
        get: operations["stream_canvas_events_api_v1_canvases_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Canvas */
        get: operations["get_canvas_api_v1_canvases__canvas_id__get"];
        put?: never;
        post?: never;
        /** Delete Canvas */
        delete: operations["delete_canvas_api_v1_canvases__canvas_id__delete"];
        options?: never;
        head?: never;
        /** Rename Canvas */
        patch: operations["rename_canvas_api_v1_canvases__canvas_id__patch"];
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/agents/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Direct Agent Run */
        post: operations["start_direct_agent_run_api_v1_canvases__canvas_id__agents_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/builds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Canvas Build */
        post: operations["start_canvas_build_api_v1_canvases__canvas_id__builds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Persist Canvas Layout */
        put: operations["persist_canvas_layout_api_v1_canvases__canvas_id__layout_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/layout/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Canvas Layout */
        post: operations["reset_canvas_layout_api_v1_canvases__canvas_id__layout_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_v1_canvases__canvas_id__messages_get"];
        put?: never;
        /** Post Message */
        post: operations["post_message_api_v1_canvases__canvas_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/papers/from-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Paper Link */
        post: operations["submit_paper_link_api_v1_canvases__canvas_id__papers_from_link_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/papers/{paper_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Paper */
        delete: operations["remove_paper_api_v1_canvases__canvas_id__papers__paper_id__delete"];
        options?: never;
        head?: never;
        /** Update Paper */
        patch: operations["update_paper_api_v1_canvases__canvas_id__papers__paper_id__patch"];
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/papers/{paper_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Paper */
        post: operations["retry_paper_api_v1_canvases__canvas_id__papers__paper_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/papers/{paper_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Review */
        patch: operations["update_review_api_v1_canvases__canvas_id__papers__paper_id__review_patch"];
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/papers/{paper_id}/review/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Review */
        post: operations["regenerate_review_api_v1_canvases__canvas_id__papers__paper_id__review_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/relationships/{relationship_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Relationship */
        delete: operations["remove_relationship_api_v1_canvases__canvas_id__relationships__relationship_id__delete"];
        options?: never;
        head?: never;
        /** Update Relationship */
        patch: operations["update_relationship_api_v1_canvases__canvas_id__relationships__relationship_id__patch"];
        trace?: never;
    };
    "/api/v1/canvases/{canvas_id}/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Undo Change */
        post: operations["undo_change_api_v1_canvases__canvas_id__undo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Dependencies */
        get: operations["health_dependencies_api_v1_health_dependencies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect Run */
        get: operations["inspect_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Run */
        post: operations["cancel_run_api_v1_runs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/event-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Replay Run Events */
        get: operations["replay_run_events_api_v1_runs__run_id__event_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run Events */
        get: operations["stream_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Run */
        post: operations["retry_run_api_v1_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Timeline */
        get: operations["get_run_timeline_api_v1_runs__run_id__timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentRunDetail */
        AgentRunDetail: {
            /** Agent Name */
            agent_name: string;
            /** Canvas Id */
            canvas_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Trueforge Session Id */
            trueforge_session_id?: string | null;
            /** Trueforge Turn Id */
            trueforge_turn_id?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AgentRunEventRead */
        AgentRunEventRead: {
            /** Canvas Id */
            canvas_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Run Id */
            run_id: string;
            /** Type */
            type: string;
        };
        /** AgentRunRead */
        AgentRunRead: {
            /** Canvas Id */
            canvas_id: string;
            /** Id */
            id: string;
            /** Paper Id */
            paper_id?: string | null;
            /** Status */
            status: string;
        };
        /** CanvasCreate */
        CanvasCreate: {
            /** Name */
            name: string;
            /** Research Goal */
            research_goal: string;
        };
        /** CanvasLayoutUpdate */
        CanvasLayoutUpdate: {
            /** Positions */
            positions: components["schemas"]["PaperLayoutPosition"][];
        };
        /** CanvasSnapshot */
        CanvasSnapshot: {
            canvas: components["schemas"]["CanvasSummary"];
            /** Papers */
            papers?: components["schemas"]["PaperRead"][];
            /** Relationships */
            relationships?: components["schemas"]["RelationshipRead"][];
        };
        /** CanvasSummary */
        CanvasSummary: {
            /** Build Status */
            build_status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Research Brief */
            research_brief?: {
                [key: string]: unknown;
            } | null;
            /** Research Goal */
            research_goal: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CanvasUpdate */
        CanvasUpdate: {
            /** Name */
            name: string;
        };
        /** ChatMessageCreate */
        ChatMessageCreate: {
            /** Content */
            content: string;
            /** Paper Ids */
            paper_ids?: string[];
        };
        /** ChatMessageRead */
        ChatMessageRead: {
            /** Agent Name */
            agent_name: string;
            /** Canvas Id */
            canvas_id: string;
            /** Content */
            content: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Paper Id */
            paper_id?: string | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Status */
            status: string;
        };
        /** ChatSubmission */
        ChatSubmission: {
            message: components["schemas"]["ChatMessageRead"];
            /** Queued */
            queued: boolean;
            run?: components["schemas"]["AgentRunRead"] | null;
        };
        /** DependencyHealthRead */
        DependencyHealthRead: {
            /** Academic Apis */
            academic_apis: {
                [key: string]: string;
            };
            /** Local Storage */
            local_storage: {
                [key: string]: number | string;
            };
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /** DirectAgentCreate */
        DirectAgentCreate: {
            /**
             * Agent
             * @enum {string}
             */
            agent: "main" | "discovery" | "reviewer" | "connection";
            /** Paper Ids */
            paper_ids?: string[];
            /** Prompt */
            prompt: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthRead */
        HealthRead: {
            /** Api */
            api: string;
            /** Brightdata Api Key Configured */
            brightdata_api_key_configured: boolean;
            /** Brightdata Mcp Configured */
            brightdata_mcp_configured: boolean;
            /** Database */
            database: string;
            /** Openai Configured */
            openai_configured: boolean;
            /** Required Configuration */
            required_configuration: string;
            /** Research Providers */
            research_providers: {
                [key: string]: string;
            };
            /** Status */
            status: string;
            /** Trueforge */
            trueforge: string;
            /** Trueforge Url */
            trueforge_url: string;
        };
        /** PaperLayoutPosition */
        PaperLayoutPosition: {
            /** Paper Id */
            paper_id: string;
            /** Pinned */
            pinned: boolean;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** PaperLinkCreate */
        PaperLinkCreate: {
            /** Url */
            url: string;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
        };
        /** PaperRead */
        PaperRead: {
            /** Authors */
            authors: string[];
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Link */
            link: string;
            /** Month */
            month: number | null;
            /**
             * Pinned
             * @default false
             */
            pinned: boolean;
            /** Plain Language Summary */
            plain_language_summary?: string | null;
            /** Processing Status */
            processing_status: string;
            /** Review */
            review?: {
                [key: string]: string;
            } | null;
            /** Summary */
            summary: string;
            /** Title */
            title: string;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Y
             * @default 0
             */
            y: number;
            /** Year */
            year: number | null;
        };
        /** PaperUpdate */
        PaperUpdate: {
            /** Authors */
            authors?: string[] | null;
            /** Link */
            link?: string | null;
            /** Month */
            month?: number | null;
            /** Pinned */
            pinned?: boolean | null;
            /** Summary */
            summary?: string | null;
            /** Title */
            title?: string | null;
            /** X */
            x?: number | null;
            /** Y */
            y?: number | null;
            /** Year */
            year?: number | null;
        };
        /** RelationshipEdit */
        RelationshipEdit: {
            /** Explanation */
            explanation?: string | null;
            /** Label */
            label?: string | null;
        };
        /** RelationshipRead */
        RelationshipRead: {
            /** Explanation */
            explanation: string;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Source */
            source: string;
            /** Target */
            target: string;
            /**
             * Type
             * @enum {string}
             */
            type: "extends" | "contradicts" | "same_benchmark" | "uses_method" | "cites" | "related";
        };
        /** ReviewEdit */
        ReviewEdit: {
            /** Sections */
            sections: {
                [key: string]: string;
            };
        };
        /** RunTimelineRead */
        RunTimelineRead: {
            /** Duration Ms */
            duration_ms?: number | null;
            /** Events */
            events: components["schemas"]["AgentRunEventRead"][];
            run: components["schemas"]["AgentRunDetail"];
            /** Tool Invocations */
            tool_invocations: components["schemas"]["ToolInvocationRead"][];
            /** Usage */
            usage?: {
                [key: string]: number;
            };
        };
        /** ToolInvocationRead */
        ToolInvocationRead: {
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Completed At */
            completed_at?: string | null;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Result */
            result?: unknown | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Status */
            status: string;
            /** Tool Name */
            tool_name: string;
        };
        /** UndoRead */
        UndoRead: {
            /** Undo Token */
            undo_token: string;
        };
        /** UndoRequest */
        UndoRequest: {
            /** Undo Token */
            undo_token: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_canvases_api_v1_canvases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSummary"][];
                };
            };
        };
    };
    create_canvas_api_v1_canvases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_canvas_events_api_v1_canvases_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_canvas_api_v1_canvases__canvas_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_canvas_api_v1_canvases__canvas_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_canvas_api_v1_canvases__canvas_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_direct_agent_run_api_v1_canvases__canvas_id__agents_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectAgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_canvas_build_api_v1_canvases__canvas_id__builds_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    persist_canvas_layout_api_v1_canvases__canvas_id__layout_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CanvasLayoutUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_canvas_layout_api_v1_canvases__canvas_id__layout_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_v1_canvases__canvas_id__messages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_message_api_v1_canvases__canvas_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_paper_link_api_v1_canvases__canvas_id__papers_from_link_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_paper_api_v1_canvases__canvas_id__papers__paper_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_paper_api_v1_canvases__canvas_id__papers__paper_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaperUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_paper_api_v1_canvases__canvas_id__papers__paper_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_review_api_v1_canvases__canvas_id__papers__paper_id__review_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_review_api_v1_canvases__canvas_id__papers__paper_id__review_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                paper_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_relationship_api_v1_canvases__canvas_id__relationships__relationship_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_relationship_api_v1_canvases__canvas_id__relationships__relationship_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelationshipEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    undo_change_api_v1_canvases__canvas_id__undo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                canvas_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UndoRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanvasSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRead"];
                };
            };
        };
    };
    health_dependencies_api_v1_health_dependencies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DependencyHealthRead"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                canvas_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inspect_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v1_runs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_run_events_api_v1_runs__run_id__event_log_get: {
        parameters: {
            query?: {
                after_id?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunEventRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_run_api_v1_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_timeline_api_v1_runs__run_id__timeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTimelineRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
